### ISSUE TITLE
Importing vespa causes circular import

### ISSUE THREAD

**Issue by yk** [vespa-engine/learntorank#8]
This line here:
https://github.com/vespa-engine/learntorank/blob/083b4197bedbc3783f8ccf3bb25974511219ddc3/learntorank/query.py#L13
causes a circular import.

**Comment by thigm85** [comment]
Yes, https://github.com/vespa-engine/pyvespa/pull/382 solves this. `learntorank` will depend on `pyvespa` but not the other way around. We are moving ML-related code from `pyvespa` to `learntorank`.

**Comment by yk** [comment]
thank you :) it was just that the current `pip install vespa` breaks things bc the fix is not in yet, but it pulls `learntorank==0.14`.
Good to close this

**Comment by thigm85** [comment]
The fix is now on PyPI with [pyvespa version 0.30.0](https://github.com/vespa-engine/pyvespa/releases/tag/v0.30.0).
